# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.





# Site settings
title: "Code; Build; Wait; Wait; Test; Repeat;"
username: Vasili Puchko
description: > # this means to ignore newlines until "baseurl:"
 Hello, my name is Vasili Puchko and I welcome you at my personal blog where I post my ideas, projects and rumblings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zihotki.github.com" # the base hostname & protocol for your site

github_username: zihotki
github_avatarUrl: "https://avatars3.githubusercontent.com/u/114631?v=3&s=180"
facebook_username: zihotki
linkedin_username: zihotki

ms_validate: sdfasdf
google_validate: 9zqfhfU0kc5Zr3eqnbazjbEYT_r568VHudVmYLnhl18
google_analytics_id: UA-8099125-3


# Gems
gems: 
- jekyll-archives
- jekyll-paginate

# Config
paginate: 10
paginate_path: "page/:num"
# Build settings
markdown: kramdown

# Archive
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
