source 'https://rubygems.org'
gem 'wdm', '~> 0.1.1' if Gem.win_platform?
gem 'thor'
gem 'stringex'
gem 'jekyll-paginate'
gem 'kramdown'
gem 'jekyll-watch'
gem 'jekyll-archives'
gem 'jekyll'
gem 'json'
